title: My Jekyll Site
description: A website built with Jekyll and hosted on GitHub Pages
baseurl: ""  # Leave empty if deployed to GitHub Pages root, or set to "/subfolder" for custom domains
url: "https://yourusername.github.io"  # Replace with your GitHub username or custom domain

theme: jekyll-theme-primer  # Optional: Choose a different theme or keep the default

source: "./docs"  # Ensure this points to the correct source folder for your content

sass:
  style: compressed  # Optional: Compresses the CSS output
  load_paths:
    - "assets/css"  # This ensures the SCSS files in this folder are available to Jekyll

# Uncomment to enable Google Analytics (or any other integrations)
# google_analytics: "UA-XXXXXXXXX"
