# _config.yml
title: My Jekyll Site
description: A website built with Jekyll and hosted on GitHub Pages
baseurl: ""  # If deployed to GitHub Pages root, leave it empty
url: "https://username.github.io"  # Replace 'username' with your GitHub username
theme: jekyll-theme-primer  # You can change the theme if desired

# Optionally, you can add Google Analytics or other settings below:
# google_analytics: UA-XXXXXXXXX
