# _config.yml

title: My Jekyll Site
email: your-email@example.com
description: "A simple Jekyll site."
baseurl: ""  # The base URL of your site
url: "https://your-github-username.github.io"  # The full URL for your GitHub Pages site
markdown: kramdown

theme: jekyll-theme-primer  # You can change this to another theme or custom theme

# Source and Destination directories
source: docs
destination: docs/_site

# Optional: Exclude certain files from being copied to the site
exclude:
  - ".jekyll-cache"
  - ".git"
  - ".DS_Store"
  - "README.md"
  - "LICENSE.md"
  - "node_modules"

# Build settings
future: false
highlighter: rouge
sass:
  style: compressed
