services:
  - type: web
    name: meal-api
    env: java
    plan: free
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/meal-api-0.0.1-SNAPSHOT.jar
    runtime: 
    branches:
      - master
